[package]
name = "spelling-corrector"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dym = "1.0.1"
once_cell = "1.7.2"

[features]
wizer = []
