[workspace]
members = [
  "benchmarks",
  "hello",
  "markdown",
  "spelling-corrector",
]

# [profile.bench]
# debug = true

# [patch.crates-io]
# wasmtime = { path = "../wasmtime/crates/wasmtime" }
