[workspace]
members = [
  "benchmarks",
  "hello",
  "markdown",
  "spelling-corrector",
]

# [profile.bench]
# debug = true

[patch.crates-io]
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime.git" }
